#!/usr/bin/env  php
<?php
$applicationName="build";
// better set to php.ini phar.readonly = 0
if (isset($argv[1])) {
    $outdir = $argv[1];
}
else {
    $outdir = "./bin";
}
if (!file_exists($outdir)) {
    mkdir($outdir);
}
ini_set("phar.readonly", 0); 
$pharFile = $outdir . '/'.$applicationName.'.phar';
$pharFileGz = $pharFile . '.gz';

// clean up
if (file_exists($pharFile)) {
    unlink($pharFile);
}
if (file_exists($pharFileGz)) {
    unlink($pharFileGz);
}

// create phar
$p = new Phar($pharFile);
// creating our library using whole directory  
$p->buildFromDirectory('.');
// pointing main file which requires all classes  
$p->setDefaultStub('index.php', '/index.php');

//plus - compressing it into gzip  
$p->compress(Phar::GZ);

unlink($pharFile);
rename($pharFileGz, $pharFile);
